version: "3.9"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports: 
      - 5432:5432
    volumes:
      - ./src/database/database.sql:/docker-entrypoint-initdb.d/init.sql


  api:
    container_name: api
    build: .
    depends_on: 
      - postgres
    links:
      - postgres
    ports:
      - 8080:8080
    command: npm start
